name: CD workflow in vke

on:
  push:
    branches:
      - production
      - check-cd-work

jobs:
  main-job:
    runs-on: ubuntu-20.04
    environment:
      name: prod

    steps:
      ### Build Jar Application ###
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          check-latest: true

      - name: Build Jar with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
          arguments: build

      ### Dockerize ###
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Show tree
        run:
          sudo apt-get install -y tree
          tree

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/noname2048/cw:latest

      ### Rolling Update ###
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3

      - name: Set kubeconfig (context)
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to kubernetes
        run: |
          kubectl rollout restart deployment/cw-deployment -n cw
