name: CI Workflow

on:
  pull_request:
    branches:
      - depreciated

jobs:
  ci-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          check-latest: true

      - name: Setup Gradle and test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
          arguments: test
          gradle-home-cache-cleanup: true
